version: '3.8'

services:
  # mysql container
  database:
    container_name: database
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony_docker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - full-project

  # phpmyadmin container
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8100:80"
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
    depends_on:
      - database
    networks:
      - full-project

  # php container
  php:
    container_name: php
    image: php:fpm-alpine
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./symfony:/var/www/symfony_docker
    depends_on:
      - database
    networks:
      - full-project

  # nginx container
  nginx:
    container_name: nginx
    image: nginx:1.25.3-alpine
    ports:
      - '8080:80'
    volumes:
      - ./symfony:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
    networks:
      - full-project

networks:
  full-project:
    driver: bridge
